name: Matrix demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12,14,16]
        operating-system: [ubuntu-latest, windows-latest]
    # instructing workflow to run for each operating system. by default these will run parallel
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          # run for node 12,14,16 
          node-version: $${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
