name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string # this is a mandatory argument
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}# we want the name, the name of other workflow generated code/artifact files. instead of hardcode name
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying and uploading..."
